include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    unnecessary_new: true
    unnecessary_null_in_if_null_operators: true
    prefer_is_empty: true
    prefer_is_not_empty: true


